DROP TABLE IF EXISTS JOB;

CREATE TABLE JOB(
  ID SERIAL PRIMARY KEY,
  JOB_NAME TEXT NOT NULL,
  JOB_DESCRIPTION TEXT NOT NULL,
  SALARY NUMERIC(10,2) NOT NULL
);

GRANT SELECT, INSERT ON JOB TO test;

ALTER TABLE PERSON ADD JOB_ID INTEGER;

ALTER TABLE PERSON
  ADD CONSTRAINT FK_JOB_PERSON FOREIGN KEY (JOB_ID) REFERENCES JOB;